- name: copy module
  hosts: ansible
  become: true
  vars:
    src_path: /root/Dockerfile
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/my project/Dockerfile
        dest: /root
        mode: '0644'

    - name: Run the Linux command
      ansible.builtin.command:
        cmd: "docker buid -t vicky . {{ src_path }}"

    - name: run docker 
      ansible.builtin.command:
        cmd: docker run -itd --name ganesh -p 8090:8080 vicky

    - name: copy war
      ansible.builtin.command:
        cmd: cp target/newapp.war /usr/local/tomcat/webapps/





