- name: copy module
  hosts: ansible
  become: true
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/my project/Dockerfile
        dest: /root
        mode: '0644'

    - name: copy war
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/my project/target/newapp.war
        dest: /home/ec2-user
        mode: '0644'


    - name: Run the Linux command
      ansible.builtin.command:
        cmd: docker build -t vickyssssdsss .

    - name: run docker 
      ansible.builtin.command:
        cmd: docker run -itd --name ganeshssssdsss -p 8099:8080 vickyssssdsss

    - name: copy
      shell: docker cp /home/ec2-user/newapp.war vickyssssdsss:/usr/local/tomcat/webapps

    





