- name: copy module
  hosts: ansible
  become: true
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/my project/Dockerfile
        dest: /root
        mode: '0644'

    - name: Run the Linux command
      ansible.builtin.command:
        cmd: docker buid -t vicky . /root/Dockerfile

    - name: run docker 
      ansible.builtin.command:
        cmd: docker run -itd --name ganesh -p 8090:8080 vicky

    - name: copy war
      ansible.builtin.command:
        src: /target/newapp.war
        dest: /usr/local/tomcat/webapps/
        mode: '0644'





