- name: copy module
  hosts: ansible
  become: true
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/newproject/Dockerfile
        dest: /root
        mode: '0644'

    - name: copy war
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/newproject/target/newapp.war
        dest: /home/ec2-user
        mode: '0644'


    - name: Run the Linux command
      command: docker build -t vicky /root


    - name: rm
      ansible.builtin.command:
        cmd: docker rm -f hari

    - name: run docker 
      ansible.builtin.command:
        cmd: docker run -itd --name hari -p 8085:8080 vicky

    - name: copy
      shell: docker cp /home/ec2-user/newapp.war hari:/usr/local/tomcat/webapps

    





